In [10]:
import pandas as pd
import requests
import io
from dataexp import Dataexp
from google.cloud import storage
from datetime import datetime

In [60]:
URL = "https://data.wa.gov/resource/f6w7-q2d2.csv"

LIMIT = 100_000
OFFSET = 0

chunks = []
dtype = {'vin_1_10': 'string',
         'county': 'string',
         'city': 'string',
         'state': 'string',
         'zip_code': 'string',
         'model_year': 'int32',
         'make': 'string',
         'model': 'string',
         'ev_type': 'string',
         'cafv_type': 'string',
         'electric_range': 'float32',
         'legislative_district': 'string',
         'dol_vehicle_id': 'string', 
         'geocoded_column': 'string', 
         'electric_utility': 'string',
         '_2020_census_tract': 'string'}

with requests.Session() as session:
    while True:
        response = session.get(
            URL,
            params={
                "$limit": LIMIT,
                "$offset": OFFSET,
            },
            timeout=600,
        )
        response.raise_for_status()

        chunk = pd.read_csv(io.BytesIO(response.content), dtype=dtype)

        if chunk.empty:
            print("No more rows to download.")
            break

        chunks.append(chunk)

        OFFSET += len(chunk)

        print(f"Retrieved {OFFSET:,} rows")

        if len(chunk) < LIMIT:
            print("No more rows to download.")
            break

df = pd.concat(chunks, ignore_index=True)
parquet_bytes = df.to_parquet()

Retrieved 100,000 rows
Retrieved 200,000 rows
Retrieved 299,705 rows
No more rows to download.

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 299705 entries, 0 to 299704
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   vin_1_10              299705 non-null  string
 1   county                299694 non-null  string
 2   city                  299694 non-null  string
 3   state                 299705 non-null  string
 4   zip_code              299694 non-null  string
 5   model_year            299705 non-null  int32
 6   make                  299705 non-null  string
 7   model                 299705 non-null  string
 8   ev_type               299705 non-null  string
 9   cafv_type             299705 non-null  string
 10  electric_range        299679 non-null  float32
 11  legislative_district  298915 non-null  string
 12  dol_vehicle_id        299705 non-null  string
 13  geocoded_column       299685 non-null  string
 14  electric_utility      299694 non-null  string
 15  _2020_census_tract    299694 non-null  string
dtypes: float32(1), int32(1), string(14)
memory usage: 97.4 MB

In [28]:
now = datetime.now()

storage_client = storage.Client(project='data-engineer-project-506916')
bucket = storage_client.bucket('ev_population_data_pipeline_bucket')

blob = bucket.blob(f'{now.year}-{now.strftime('%b')} ev_population_data.parquet')
blob.upload_from_string(parquet_bytes)
print('Successfully upload data to Google cloud storage')

Successfully upload data to Google cloud storage

In [29]:
blob = bucket.blob(f'{now.year}-{now.strftime('%b')} ev_population_data.parquet')
contents = io.BytesIO(blob.download_as_bytes())

df = pd.read_parquet(contents)
print('Finished Download and Load to DataFrame')

Finished Download and Load to DataFrame

In [62]:
df_copy = df.copy()

In [106]:
df_copy.head()

,vin_1_10,county,city,state,zip_code,model_year,make,model,ev_type,cafv_type,electric_range,legislative_district,geocoded_column,electric_utility,_2020_census_tract
dol_vehicle_id,,,,,,,,,,,,,,,
168526641,1n4az1cp3k,king,shoreline,wa,98155,2019,nissan,leaf,battery electric vehicle (bev),clean alternative fuel vehicle eligible,150.0,32,point (-122.30304 47.75494),city of seattle - (wa)|city of tacoma - (wa),53033020500
9418181,wby8p4c51k,king,kirkland,wa,98033,2019,bmw,i3,plug-in hybrid electric vehicle (phev),clean alternative fuel vehicle eligible,126.0,48,point (-122.2066 47.67887),puget sound energy inc||city of tacoma - (wa),53033022703
172853495,3fa6p0su8g,snohomish,lynnwood,wa,98036,2016,ford,fusion,plug-in hybrid electric vehicle (phev),not eligible due to low battery range,19.0,1,point (-122.29245 47.82557),puget sound energy inc,53061051932
204768175,5yj3e1eb3n,yakima,wapato,wa,98951,2022,tesla,model 3,battery electric vehicle (bev),eligibility unknown as battery range has not b...,0.0,15,point (-120.42083 46.44779),pacificorp,53077940008
269262920,wby1z2c53f,king,renton,wa,98055,2015,bmw,i3,battery electric vehicle (bev),clean alternative fuel vehicle eligible,81.0,11,point (-122.19488 47.44034),puget sound energy inc||city of tacoma - (wa),53033025805

In [72]:
exp = Dataexp(df_copy)

In [73]:
exp.dtypes

{'O': [('vin_1_10', 'string'),
  ('county', 'string'),
  ('city', 'string'),
  ('state', 'string'),
  ('zip_code', 'string'),
  ('make', 'string'),
  ('model', 'string'),
  ('ev_type',
   'category',
   ['battery electric vehicle (bev)',
    'plug-in hybrid electric vehicle (phev)']),
  ('cafv_type',
   'category',
   ['clean alternative fuel vehicle eligible',
    'eligibility unknown as battery range has not been researched',
    'not eligible due to low battery range']),
  ('legislative_district', 'string'),
  ('geocoded_column', 'string'),
  ('electric_utility', 'string'),
  ('_2020_census_tract', 'string')],
 'i': [('model_year', 'int32')],
 'f': [('electric_range', 'float32')]}

In [35]:
categories = {'cafv_type': 
                  {'clean alternative fuel vehicle eligible',
                   'eligibility unknown as battery range has not been researched',
                   'not eligible due to low battery range', 
                   'not defined'},
              'ev_type': 
                  {'battery electric vehicle (bev)', 
                   'plug-in hybrid electric vehicle (phev)',
                   'not defined'}}

In [69]:
df_copy = df.apply(lambda x: x.str.lower().str.strip() if x.dtype.name == 'string' else x)
df_copy.set_index('dol_vehicle_id', inplace=True)

for key, val in categories.items():
    diff = set(df_copy[key].unique()) - val
    print(diff)
    
    df_copy.loc[df_copy[key].isin(diff), key] = 'not defined'
    print('Success')

    df_copy[key] = df_copy[key].astype('category')

null = df.isnull().any(axis=1)

null_df = df[null]
clean_df = df[~null]

set()
Success
set()
Success

In [74]:
exp.null

vin_1_10                  0
county                   11
city                     11
state                     0
zip_code                 11
model_year                0
make                      0
model                     0
ev_type                   0
cafv_type                 0
electric_range           26
legislative_district    790
geocoded_column          20
electric_utility         11
_2020_census_tract       11
dtype: int64

In [75]:
df[df.isnull().any(axis=1)].sample(50)

,vin_1_10,county,city,state,zip_code,model_year,make,model,ev_type,cafv_type,electric_range,legislative_district,dol_vehicle_id,geocoded_column,electric_utility,_2020_census_tract
295590,5YJXCDE26L,Harris,Houston,TX,77002,2020,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,289.0,<NA>,2606453,POINT (-95.36952 29.76078),NON WASHINGTON STATE ELECTRIC UTILITY,48201980700
297115,7SAYGDEF5N,Montgomery,Montgomery,AL,36113,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,289782230,POINT (-86.34036 32.3804),NON WASHINGTON STATE ELECTRIC UTILITY,01101000900
279972,5YJ3E1EA2P,San Diego,San Diego,CA,92109,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,235160782,POINT (-117.25114 32.79099),NON WASHINGTON STATE ELECTRIC UTILITY,06073007602
299681,7SAYGDEF5N,Broward,Fort Lauderdale,FL,33312,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,209149209,POINT (-80.2002 26.087),NON WASHINGTON STATE ELECTRIC UTILITY,12011080406
295895,5YJ3E1EB4M,Santa Clara,San Jose,CA,95126,2021,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,268060964,POINT (-121.91016 37.32799),NON WASHINGTON STATE ELECTRIC UTILITY,06085502203
283710,5YJ3E1EA7R,Wayne,Pikeville,NC,27863,2024,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,272809477,POINT (-77.98164 35.49815),NON WASHINGTON STATE ELECTRIC UTILITY,37191000303
285357,5YJSA1E50N,Cook,Chicago,IL,60659,2022,TESLA,MODEL S,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,195204551,POINT (-87.69926 41.99044),NON WASHINGTON STATE ELECTRIC UTILITY,17031020802
249693,7SAYGDEE4N,El Paso,Monument,CO,80132,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,195647805,POINT (-104.87157 39.09153),NON WASHINGTON STATE ELECTRIC UTILITY,08041007301
190011,7SAYGDEE5R,Clark,Las Vegas,NV,89148,2024,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,265090031,POINT (-115.30437 36.07015),NON WASHINGTON STATE ELECTRIC UTILITY,32003005860
297829,JTDKAMFP4M,Clark,Las Vegas,NV,89130,2021,TOYOTA,PRIUS PRIME (PHEV),Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25.0,<NA>,259285869,POINT (-115.23121 36.24776),NON WASHINGTON STATE ELECTRIC UTILITY,32003003428
289511,5YJ3E1EA0L,Chesapeake,Chesapeake,VA,23323,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,266.0,<NA>,8334952,POINT (-76.3399 36.78235),NON WASHINGTON STATE ELECTRIC UTILITY,51550021304
183895,JTMAB3FV8P,Riverside,Winchester,CA,92596,2023,TOYOTA,RAV4 PRIME (PHEV),Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,42.0,<NA>,244872925,POINT (-117.13765 33.6914),NON WASHINGTON STATE ELECTRIC UTILITY,06065042737
271533,1N4AZ1CP1K,Hamilton,Fishers,IN,46037,2019,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,150.0,<NA>,151652567,POINT (-85.92891 39.9785),NON WASHINGTON STATE ELECTRIC UTILITY,18057110807
281205,7SAYGDEE9T,Travis,Austin,TX,78735,2026,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,290514647,POINT (-97.86826 30.26384),NON WASHINGTON STATE ELECTRIC UTILITY,48453001921
278512,7SAYGDEE1R,Alexandria,Alexandria,VA,22304,2024,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,276704221,POINT (-77.12363 38.81125),NON WASHINGTON STATE ELECTRIC UTILITY,51510200404
179232,7SAYGDEE9P,Solano,Fairfield,CA,94533,2023,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,253501272,POINT (-122.0443 38.24924),NON WASHINGTON STATE ELECTRIC UTILITY,06095252317
140178,7SAYGAEE9N,Santa Clara,Milpitas,CA,95035,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,220637546,POINT (-121.89694 37.43288),NON WASHINGTON STATE ELECTRIC UTILITY,06085504509
270241,1C4RJXR68R,Douglas,Stateline,NV,89449,2024,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,<NA>,279060939,POINT (-119.93917 38.96348),NON WASHINGTON STATE ELECTRIC UTILITY,32005001800
288200,VCF1ZBU27P,Butte,Belle Fourche,SD,57717,2023,FISKER,OCEAN,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,273710412,POINT (-103.85289 44.67145),NON WASHINGTON STATE ELECTRIC UTILITY,46019967701
291715,7FCTGBAA7R,Orange,Laguna Beach,CA,92651,2024,RIVIAN,R1T,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,273778256,POINT (-117.78407 33.54243),NON WASHINGTON STATE ELECTRIC UTILITY,06059062649
287961,YV4ED3UR4N,El Paso,Colorado Springs,CO,80921,2022,VOLVO,XC40,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,252674950,POINT (-104.83147 39.03647),NON WASHINGTON STATE ELECTRIC UTILITY,08041007205
275941,1C4RJYD64N,Fairfax,Vienna,VA,22180,2022,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25.0,<NA>,257712507,POINT (-77.26399 38.90063),NON WASHINGTON STATE ELECTRIC UTILITY,51059460702
181026,7SAYGDEE7T,Prince George,Fort Lee,VA,23801,2026,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,284733543,POINT (-77.34504 37.24287),NON WASHINGTON STATE ELECTRIC UTILITY,51149850200
284588,1FT6W3L74R,Pasco,Wesley Chapel,FL,33544,2024,FORD,F-150,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,274976271,POINT (-82.36013 28.18581),NON WASHINGTON STATE ELECTRIC UTILITY,12101032106
245982,WBS83FK03S,Boulder,Louisville,CO,80027,2025,BMW,M5,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25.0,<NA>,278870042,POINT (-105.14238 39.92832),NON WASHINGTON STATE ELECTRIC UTILITY,08013013005
296201,5YJ3E1EB9J,Maui,Kihei,HI,96753,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,<NA>,474346092,POINT (-156.46349 20.78276),NON WASHINGTON STATE ELECTRIC UTILITY,15009030307
297579,2C4RC1S77M,Montgomery,Gaithersburg,MD,20878,2021,CHRYSLER,PACIFICA,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,32.0,<NA>,176092668,POINT (-77.23908 39.12004),NON WASHINGTON STATE ELECTRIC UTILITY,24031700604
296166,KNDRMDLHXN,Chesapeake,Chesapeake,VA,23323,2022,KIA,SORENTO,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,32.0,<NA>,211179811,POINT (-76.3399 36.78235),NON WASHINGTON STATE ELECTRIC UTILITY,51550021402
280266,7SAYGDEE5N,Maricopa,Phoenix,AZ,85053,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,224048380,POINT (-112.1354 33.62525),NON WASHINGTON STATE ELECTRIC UTILITY,04013104207
229791,1C4JJXN69P,San Diego,San Diego,CA,92106,2023,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,<NA>,289865649,POINT (-117.22463 32.73243),NON WASHINGTON STATE ELECTRIC UTILITY,06073021401
292881,KNDC3DLC0P,Fairfax,Oakton,VA,22124,2023,KIA,EV6,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,252544862,POINT (-77.30116 38.8809),NON WASHINGTON STATE ELECTRIC UTILITY,51059481701
223847,JTJHKCFZXS,San Diego,Chula Vista,CA,91915,2025,LEXUS,NX,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,37.0,<NA>,291451842,POINT (-116.95723 32.62445),NON WASHINGTON STATE ELECTRIC UTILITY,06073013320
116158,1V2JSPE89T,Lake,Libertyville,IL,60048,2026,VOLKSWAGEN,ID.4,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,292889089,POINT (-88.01512 42.32119),NON WASHINGTON STATE ELECTRIC UTILITY,17097864106
230099,WA1LUBFZ9R,Chesapeake,Chesapeake,VA,23322,2024,AUDI,Q4,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,284300656,POINT (-76.24779 36.71428),NON WASHINGTON STATE ELECTRIC UTILITY,51550021004
265564,JTJAAAAB6R,Travis,Leander,TX,78641,2024,LEXUS,RZ,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,268176268,POINT (-97.81353 30.54391),NON WASHINGTON STATE ELECTRIC UTILITY,48453036100
248071,JTDKAMFP9N,<NA>,<NA>,AE,<NA>,2022,TOYOTA,PRIUS PRIME (PHEV),Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25.0,<NA>,198537741,<NA>,<NA>,<NA>
269051,5YJ3E1EA6M,Maricopa,Phoenix,AZ,85016,2021,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,175487007,POINT (-112.02769 33.49489),NON WASHINGTON STATE ELECTRIC UTILITY,04013110702
278964,3FMTK3SU5P,Clark,Las Vegas,NV,89119,2023,FORD,MUSTANG MACH-E,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,257685144,POINT (-115.13452 36.1009),NON WASHINGTON STATE ELECTRIC UTILITY,32003002847
292602,KM8KRDAF6P,Virginia Beach,Virginia Beach,VA,23456,2023,HYUNDAI,IONIQ 5,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,280690343,POINT (-76.05968 36.75531),NON WASHINGTON STATE ELECTRIC UTILITY,51810045434
261533,1N4AZ0CP0G,Los Angeles,Calabasas,CA,91302,2016,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,<NA>,317616680,POINT (-118.69328 34.15233),NON WASHINGTON STATE ELECTRIC UTILITY,06037800104
187344,5YJ3E1EB4L,Riverside,Murrieta,CA,92562,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,322.0,<NA>,290152404,POINT (-117.21179 33.55843),NON WASHINGTON STATE ELECTRIC UTILITY,06065043278
200023,JTMAB3FV0P,Laramie,Cheyenne,WY,82001,2023,TOYOTA,RAV4 PRIME (PHEV),Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,42.0,<NA>,264509486,POINT (-104.82154 41.13481),NON WASHINGTON STATE ELECTRIC UTILITY,56021000702
296607,5YJ3E1EAXP,Burlington,Mount Laurel,NJ,08054,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,229934015,POINT (-74.89321 39.93578),NON WASHINGTON STATE ELECTRIC UTILITY,34005702909
219056,7SAYGDEE7R,Anne Arundel,Severna Park,MD,21146,2024,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,273645102,POINT (-76.54339 39.07441),NON WASHINGTON STATE ELECTRIC UTILITY,24003730606
274281,JM3KKCHA7T,Anne Arundel,Fort George G Meade,MD,20755,2026,MAZDA,CX-90,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,27.0,<NA>,292167543,POINT (-76.73522 39.10847),NON WASHINGTON STATE ELECTRIC UTILITY,24003740601
265635,5YJ3E1EB6P,Ada,Boise,ID,83702,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,229729706,POINT (-116.1934 43.60764),NON WASHINGTON STATE ELECTRIC UTILITY,16001000101
121197,WVG6YVEB9S,Lake,Libertyville,IL,60048,2025,VOLKSWAGEN,ID. BUZZ,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,286510094,POINT (-88.01512 42.32119),NON WASHINGTON STATE ELECTRIC UTILITY,17097864106
264844,7PDSGABL1N,Maui,Paia,HI,96779,2022,RIVIAN,R1S,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,284904329,POINT (-156.37177 20.90305),NON WASHINGTON STATE ELECTRIC UTILITY,15009031900
195387,5YJYGDEF0M,San Diego,San Diego,CA,92154,2021,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,<NA>,213673428,POINT (-117.09543 32.57934),NON WASHINGTON STATE ELECTRIC UTILITY,06073010017
278273,SADHD2S16L,St. Johns,Ponte Vedra,FL,32081,2020,JAGUAR,I-PACE,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,234.0,<NA>,110489613,POINT (-81.46575 30.09655),NON WASHINGTON STATE ELECTRIC UTILITY,12109020605

In [8]:
df.duplicated(subset=['vin_1_10']).sum()

np.int64(276125)

In [9]:
((df.isnull().any(axis=1).sum() / len(df)) * 100.0).round(2)

np.float64(0.27)

In [10]:
null_df = df[df.isnull().any(axis=1)]

In [11]:
clean_df = df[~df.isnull().any(axis=1)]

In [12]:
df_state = set(df['state'].unique())

In [15]:
df[df['state'].isin(df_state - states)]

,vin_1_10,county,city,state,zip_code,model_year,make,model,ev_type,cafv_type,electric_range,legislative_district,dol_vehicle_id,geocoded_column,electric_utility,_2020_census_tract
372,1G1FX6S08J,NaN,NaN,BC,NaN,2018,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238.0,NaN,272897614,NaN,NaN,NaN
243135,5YJ3E1EA6K,NaN,NaN,BC,NaN,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,NaN,323559204,NaN,NaN,NaN
252984,3FA6P0SU7E,NaN,NaN,AE,NaN,2014,FORD,FUSION,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,19.0,NaN,255045136,NaN,NaN,NaN
257860,WVGTMPE23M,NaN,NaN,AE,NaN,2021,VOLKSWAGEN,ID.4,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,NaN,179339058,NaN,NaN,NaN
265661,5YJ3E1EA5S,NaN,NaN,BC,NaN,2025,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,NaN,280877355,NaN,NaN,NaN
269448,7SAYGDEF8N,NaN,NaN,QC,NaN,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,NaN,211959226,NaN,NaN,NaN
272169,7SAYGDEE9N,NaN,NaN,BC,NaN,2022,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,NaN,224286394,NaN,NaN,NaN
276895,5YJXCAE24H,NaN,NaN,BC,NaN,2017,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,200.0,NaN,159850029,NaN,NaN,NaN
293578,JTDKAMFP9N,NaN,NaN,AE,NaN,2022,TOYOTA,PRIUS PRIME (PHEV),Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25.0,NaN,198537741,NaN,NaN,NaN

In [11]:
df.duplicated(['dol_vehicle_id']).sum()

np.int64(0)

In [16]:
set(df.ev_type.unique())

{'Battery Electric Vehicle (BEV)', 'Plug-in Hybrid Electric Vehicle (PHEV)'}

In [17]:
set(df.cafv_type.unique())

{'Clean Alternative Fuel Vehicle Eligible',
 'Eligibility unknown as battery range has not been researched',
 'Not eligible due to low battery range'}